name: build-all
on:
  push: { branches: [ main ] }
  pull_request:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Install CMake & Ninja
        run: choco install cmake ninja -y --installargs 'ADD_CMAKE_TO_PATH=System'
      - name: Fetch Geode SDK
        run: git clone --depth=1 https://github.com/geode-sdk/geode.git geode-sdk
      - name: Configure
        env: { GEODE_SDK: ${{ github.workspace }}/geode-sdk }
        run: cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - name: Build
        run: cmake --build build --config RelWithDebInfo
      - uses: actions/upload-artifact@v4
        with: { name: geode-windows, path: build/bin/*.geode }

  android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cmake ninja-build
      - id: setup-ndk
        uses: nttld/setup-ndk@v1
        with: { ndk-version: r26d }
      - run: git clone --depth=1 https://github.com/geode-sdk/geode.git geode-sdk
      - env:
          GEODE_SDK: ${{ github.workspace }}/geode-sdk }
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          cmake -S . -B build-android -G "Ninja" \
            -DGEODE_TARGET_PLATFORM=android \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_NDK="$ANDROID_NDK" \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - run: cmake --build build-android --config RelWithDebInfo
      - uses: actions/upload-artifact@v4
        with: { name: geode-android, path: build-android/bin/*.geode }

  ios:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: |
          brew update
          brew install cmake ninja
      - run: git clone --depth=1 https://github.com/geode-sdk/geode.git geode-sdk
      - env: { GEODE_SDK: ${{ github.workspace }}/geode-sdk }
        run: |
          cmake -S . -B build-ios -G Xcode \
            -DGEODE_TARGET_PLATFORM=ios \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - run: cmake --build build-ios --config RelWithDebInfo
      - uses: actions/upload-artifact@v4
        with: { name: geode-ios, path: build-ios/bin/*.geode }
