name: build-ios
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Geode CLI
        run: brew install geode-sdk/geode/geode-cli

      - name: Add dummy Geode profile
        run: geode profile add --name "CI Profile" /tmp ios

      - name: Install Geode SDK
        run: geode sdk install $HOME/geode-sdk

      - name: Install iOS loader binaries
        run: geode sdk install-binaries --platform ios

      - name: Configure (Xcode for iOS)
        run: |
          cmake -S . -B build-ios -G Xcode \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build
        run: cmake --build build-ios --config RelWithDebInfo

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: geode-ios
          path: build-ios/bin/*.geode
