name: build-ios
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ios:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Baut dein Mod für iOS und packt die .geode
      - name: Build Geode mod (iOS)
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          target: iOS          # <— wichtig
          sdk: latest          # SDK holen
          cli: latest          # CLI holen
          build-config: RelWithDebInfo

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: geode-ios
          path: ${{ steps.build.outputs.build-output }}
