name: build-ios-only
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ios:
    runs-on: macos-13
    env:
      # Deine GD-Version – passt zu deinem mod.json
      GEODE_GD_VERSION: 2.2074
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Geode SDK
        run: git clone --depth=1 https://github.com/geode-sdk/geode.git geode-sdk

      - name: Configure (Xcode for iOS)
        env:
          GEODE_SDK: ${{ github.workspace }}/geode-sdk
        run: |
          cmake -S . -B build-ios -G Xcode \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DGEODE_BUILD_FROM_SOURCE=ON \
            -DGEODE_GD_VERSION=${GEODE_GD_VERSION} \
            -DGEODE_BUILD_TESTS=OFF

      - name: Build
        run: cmake --build build-ios --config RelWithDebInfo

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: geode-ios
          path: build-ios/bin/*.geode
