name: build-ios
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Geode CLI
        run: brew install geode-sdk/geode/geode-cli

      - name: Restore Geode profile (dummy for CI)
        run: |
          mkdir -p $HOME/.local/share/geode
          cp .github/geode/config.json $HOME/.local/share/geode/config.json
          echo "Using config.json:"
          cat $HOME/.local/share/geode/config.json

      - name: Register dummy profile
        run: geode profile add --name "CI Profile" /tmp ios

      - name: Install iOS loader binaries
        run: geode sdk install-binaries --platform ios

      - name: Configure (Xcode for iOS)
        run: |
          cmake -S . -B build-ios -G Xcode \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build
        run: cmake --build build-ios --config RelWithDebInfo

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: geode-ios
          path: build-ios/bin/*.geode
