name: build-ios-only
on:
  push: { branches: [ main ] }
  workflow_dispatch:

jobs:
  ios:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      # Geode SDK holen
      - name: Fetch Geode SDK
        run: git clone --depth=1 https://github.com/geode-sdk/geode.git geode-sdk

      # Konfigurieren mit Xcode-Generator (kein brew, kein ninja nötig)
      - name: Configure (Xcode)
        env:
          GEODE_SDK: ${{ github.workspace }}/geode-sdk
        run: |
          cmake -S . -B build-ios -G Xcode \
            -DGEODE_TARGET_PLATFORM=ios \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo

      # Build
      - name: Build
        run: cmake --build build-ios --config RelWithDebInfo

      # Artefakt hochladen
      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: geode-ios
          path: build-ios/bin/*.geode
