name: build-ios
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true   # wichtig: Submodule auschecken

      - name: Verify submodule
        run: |
          git submodule status
          ls -la "$GITHUB_WORKSPACE/vendor/geode"

      - name: Install Geode CLI
        run: brew install geode-sdk/geode/geode-cli

      # <-- HIER: SDK-Pfad bekannt machen
      - name: Export GEODE_SDK for all next steps
        run: echo "GEODE_SDK=$GITHUB_WORKSPACE/vendor/geode" >> "$GITHUB_ENV"

      - name: Add dummy Geode profile
        run: geode profile add --name "CI Profile" "/tmp" mac

      # Optional: CLI auch intern auf das Submodule zeigen lassen
      - name: Set SDK path in Geode CLI (optional)
        run: geode sdk set-path "$GITHUB_WORKSPACE/vendor/geode"

      - name: Install iOS loader binaries
        run: geode sdk install-binaries --platform ios

      - name: Configure (Xcode for iOS)
        env:
          GEODE_SDK: "$GITHUB_WORKSPACE/vendor/geode"
        run: |
          cmake -S . -B build-ios -G Xcode \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build
        run: cmake --build build-ios --config RelWithDebInfo

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: geode-ios
          path: build-ios/bin/*.geode
